### ISSUE TITLE
Form Import preload?

### ISSUE THREAD

**Issue by lookingdown** [Bloggify/bootstrap-form-builder#11]
Is it possible to preload a form or import a form as json or html?
Thanks

**Comment by IonicaBizau** [comment]
That would be nice to have. Currently it's not possible...

**Comment by leijae** [comment]
Have this as a feature, and you'll have the best form-builder out there... any movement on this?

**Comment by leijae** [comment]
I'm willing to pay for this to happen.

**Comment by IonicaBizau** [comment]
Pull requests are very welcome. 😁
