### ISSUE TITLE
Suggested Enhancements

### ISSUE THREAD

**Issue by oldsilverado** [Bloggify/bootstrap-form-builder#12]
1. add  an option on a Drag & Drop Component, to add it to **bottom** of the form?
(EDIT:) my browser was faulty, on older version of chrome (steam powered)

2. The ability to **auto-increment** ID/Name field, would greatly enhance the usability, esp if you can set start number and increment step

**Comment by IonicaBizau** [comment]
I am going to close this. The drag and drop should work now. The ids should _not_ autoincrement but the recommendation would be to edit each id of the components.
