### ISSUE TITLE
Please add input types and attribues.

### ISSUE THREAD

**Issue by AshfaqAliZardariOfficial** [Bloggify/bootstrap-form-builder#14]
Hello, I'm @AshfaqAliZardariOfficial junior software engineer. I see your Repo "bootstrap-form-builder" please add some more features i.e Input Types, Input Attributes, Input Masking, etc...

                  Thank you!

Best Regards,
 github.com/AshfaqAliZardariOfficial

**Comment by IonicaBizau** [comment]
Thank you for this! Pull requests with improvements are always welcome. ✨
