### ISSUE TITLE
Initializing the app in MVC

### ISSUE THREAD

**Issue by Texas-E** [Bloggify/bootstrap-form-builder#20]
I'm having the worst experience getting this app going with .Net Core 3.1 MVC, can someone please point me in the right direction?

https://stackoverflow.com/questions/70731604/bootstrap-v4-form-builder-require-js-errors

**Comment by IonicaBizau** [comment]
Well, this is an app itself. It is not primarily intended that would be embedded in another app.

**Comment by leijae** [comment]
Right, I was essentially trying to piece together the main components to initialize, but i ended up going a different direction with it.
