### ISSUE TITLE
JSX mode for the rendering page

### ISSUE THREAD

**Issue by Emka877** [Bloggify/bootstrap-form-builder#9]
Hello,

It may be nice to add a switch on the rendering page, allowing the user to retrieve a JSX version of the rendering html code, like this:

![jsxmode](https://user-images.githubusercontent.com/325270/36426851-bad4a75a-164b-11e8-9182-3b67047c601e.jpg)

**Note**: It's not an implementation, it was just added with dev tools inspector ^^ (and text replaced with a text editor)

It would replace the following:
_class_ into _className_
_for_ into _htmlFor_

Anything that would avoid JS reserved words really.

**EDIT**

Also other things to replace are: (the image above does not reflect these)

1) Remove the comments (they are not welcome in JSX :s)
2) Add an / at the end of input tags

Have a nice day

**Comment by IonicaBizau** [comment]
I think it would be just some replacements in the final `val()` call or something like that. Contributions are welcome!

**Comment by IonicaBizau** [comment]
A tool like https://magic.reactjs.net/htmltojsx.htm can be used to convert the HTML into jsx. It is actually quite handy. :smile:
